modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="clashofclansweapons"
version="0.1.23"
displayName="clashofclansweapons"
credits="Created by Gabriele"
displayURL="http://gabrielelore.altervista.org"
logoFile="logo.png"
authors="Gabriele"

[[dependencies.clashofclansweapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




